name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_PRODUCTION_HOST }}
        username: deploy
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/backend
          git fetch origin main
          git reset --hard origin/main
          npm ci --production
          
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" > .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          
          pm2 restart backend || pm2 start npm --name "backend" -- start
          pm2 save
